### ISSUE TITLE
running with no emulator seems to lock

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.AzureStoragePersistence#48]
running this 
http://docs.particular.net/samples/azure/storage-persistence/#Nuget-v6-pre

with no emulator and break on all exceptions results in many exceptions on the server project

for example
```
Microsoft.WindowsAzure.Storage.StorageException occurred
  HResult=-2146233088
  Message=Unable to connect to the remote server
  Source=Microsoft.WindowsAzure.Storage
  StackTrace:
       at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
  InnerException: 
       HResult=-2146233079
       Message=Unable to connect to the remote server
       Source=System
       StackTrace:
            at System.Net.HttpWebRequest.GetResponse()
            at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 695
       InnerException: 
            ErrorCode=10061
            HResult=-2147467259
            Message=No connection could be made because the target machine actively refused it 127.0.0.1:10002
            NativeErrorCode=10061
            Source=System
            StackTrace:
                 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
                 at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
            InnerException: 

```

But none of them seem to bubble up to the console or log

**Comment by SeanFeldman** [comment]
How would you expect to run w/o storage account?

> No connection could be made because the target machine actively refused
it 127.0.0.1:10002

**Comment by SimonCropp** [comment]
i dont expect it to run. but i also dont expect it to silently do nothing, no log anything, not exit, not bubble, etc

**Comment by SeanFeldman** [comment]
@dbelcham it looks like configSections are still in use. Should exception be thrown?

**Comment by SimonCropp** [comment]
seems i just wasnt waiting long enough
